- name: Install syncthing
  package:
    name: syncthing
    state: present
  become: yes

- name: Generate syncthing user service
  template:
    src: syncthing.j2
    dest: /home/{{ user }}/.config/systemd/user/syncthing.service
    force: yes

- name: Start syncthing as user to generate initial config
  systemd:
    name: syncthing
    state: started
    scope: user

- name: Give time to syncthing to start
  pause:
    seconds: 10

- name: Add devices
  shell: syncthing cli config devices add --device-id {{ st_device.sid }} --name {{ st_device.name }}

- name: Stop syncthing
  systemd:
    name: syncthing
    state: stopped
    scope: user
  when: distro=="arch" or distro=="tw" or distro=="neon"
  
