- name: Update apt repo and cache (sudo apt update)
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Upgrade packages
  shell: pkcon update -y
  ignore_errors: yes
  become: yes
